name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
      # all combinations of node-version and os are run in wf in matrix from. Total runs = 3*2=6
        # node-version: [14, 16, 18]
        node-version:
          - 14
          - 16
          - 18
        os:
          - ubuntu-latest
          - windows-latest
        # will include the individual combination to the matrix run
        include:
          - node-version: 12
            os: ubuntu-latest
        # will exclude the already existing combination from the matrix run
        exclude:
          - node-version: 18
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci